FROM v2fly/v2fly-core:v5.41.0

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories && \
  apk update && apk add --no-cache vim python3 py3-pip busybox-extras supervisor \
  py3-requests py3-pysocks

CMD [ "bash" ]